# Generated by Django 3.0.3 on 2020-03-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('news', 'news'), ('tech', 'tech'), ('fashion', 'fashion'), ('politics', 'politics'), ('health', 'health'), ('entertainment', 'entertainment'), ('sport', 'sport')], max_length=20),
        ),
    ]
