# Generated by Django 3.0.3 on 2020-03-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
