# Generated by Django 3.0.3 on 2020-03-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0008_auto_20200328_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
